name: YouTube Downloader Worker

on:
  repository_dispatch:
    types: [download_video]

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 🚀 توربو ۱: استفاده از افزونه فوق‌سریع برای نصب FFmpeg (۲ ثانیه به جای ۳۰ ثانیه!)
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3

      # 🚀 توربو ۲: نصب سریع پکیج‌های پایتون
      - name: Install Python Dependencies
        run: |
          pip install -U yt-dlp pyrogram tgcrypto

      - name: Download Video (Direct Connection)
        id: download_direct
        run: |
          title=$(yt-dlp --get-title --no-check-certificate --retries 2 "${{ github.event.client_payload.url }}")
          echo "title=$title" >> $GITHUB_OUTPUT
          
          # بهینه‌سازی سرعت خود دانلودر با کانکشن‌های موازی
          yt-dlp -f "best[ext=mp4]/best" --no-check-certificate --retries 5 --fragment-retries 5 --concurrent-fragments 10 -o "video.%(ext)s" "${{ github.event.client_payload.url }}"
        continue-on-error: true

      - name: Get Final Title
        id: final_title
        run: |
          echo "val=${{ steps.download_direct.outputs.title }}" >> $GITHUB_OUTPUT

      - name: Upload Video to Telegram
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          python upload.py \
            "${{ github.event.client_payload.chat_id }}" \
            "${{ github.event.client_payload.message_id }}" \
            "${{ github.event.client_payload.status_msg_id }}" \
            "${{ steps.final_title.outputs.val }}"
